wget https://www.ip2location.com/downloads/sample.bin.db24.zip
unzip sample.bin.db24.zip
sleep 2
rm -r IP2LOCATION-COUNTRY-REGION.CSV
rm -r IP2LOCATION-COUNTRY.CSV
rm -r README.TXT
rm -r IP2LOCATION_LICENSE_AGREEMENT.PDF
mv IP-COUNTRY-REGION-CITY-LATITUDE-LONGITUDE-ZIPCODE-TIMEZONE-ISP-DOMAIN-NETSPEED-AREACODE-WEATHER-MOBILE-ELEVATION-USAGETYPE-SAMPLE.BIN x.BIN
mkdir data
cp x.BIN data
